EcoGreen/EcoGreen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.EcoGreen, name = 'EcoGreen'),
    
    path('login/', auth.LoginView.as_view(template_name="usuarios/login.html"), name='login'),
    path('logout/', auth.LogoutView.as_view(), name='logout'),


    #PATH QUE APUNTAN A APPS
    path('post/', include('apps.post.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EcoGreen/apps/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
 	
	path('listar/', views.listar_post, name = 'listar_post'),

	path('detalle/<int:pk>', views.DetallePost, name= 'detalle'),

	path('FILTRO/<int:pk>', views.FiltroXCategoria, name= 'filtro'),

	path('Alta/', views.altaPost.as_view(), name="alta_post"),
	
]

EcoGreen/apps/post/models.py
from django.db import models

# Create your models here.

class categoria(models.Model):
	nombre = models.CharField(max_length = 30)
	descripcion = models.CharField(max_length = 100000, null = False)

	def __str__(self):
		return self.nombre


class post(models.Model):
	nombre = models.CharField(max_length = 100000)
	descripcion = models.CharField(max_length = 100000, null = False)
	imagen = models.ImageField(upload_to = 'imagenes_post', null = True)

	def __str__(self):
		return self.nombre

EcoGreen/apps/usuarios/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
	pass

EcoGreen/apps/post/forms.py
from django import forms

from apps import post

from .models import post


class Formulario_alta_post(forms.ModelForm):
	

	class Meta:
		model = post
		fields = '__all__'

EcoGreen/EcoGreen/views.py
from django.shortcuts import render

from apps.post.models import categoria, post

def EcoGreen(request):

	r = categoria.objects.all()

	ctx = {}
	ctx['categorias'] = r

	
	return render(request,'EcoGreen.html',ctx)
    
    

EcoGreen/apps/post/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .models import post, categoria
from .forms import  Formulario_alta_post
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

@login_required
def listar_post(request):
	
	#CONSULTA PARA TRAER TODOS LOS PRODUCTOS
	# P QUERYSET (MUY PAECIDO A UN DICCIONARIO) QUE CONTIENE TODOS LOS PRODUCTOS QUE ESTEN EN LA BD
	p = post.objects.all()

	#CONTEXTO
	ctx = {}
	ctx['post'] = p
	ctx['titulo'] = "HOLA SOY EL TITULO"

	return render(request,'post/listar_post.html',ctx)
# EN REALIDAD EN EL TEMPLATE VOY TENER VARIABLES SEPARADAS

# pruduct QUE CONTIENE a p
# titulo


def DetallePost(request, pk):

	p = post.objects.get(pk = pk)

	ctx = {}
	ctx['post'] = p


	return render(request, 'post/detallePost.html',ctx)

@login_required
def FiltroXCategoria(request, pk):

	#TRAE SOLO LA CATEGORIA CON ESA PK
	c = categoria.objects.get(pk = pk)
	#BUSCA TODOS LOS PRODUCTOS CON UNA RELACION A ESE CATEGORIA
	p = post.objects.filter(categoria = categoria )

	ctx = {}
	ctx['post'] = p
	ctx['categoria'] = categoria

	return render(request, 'post/filtroxCategoria.html',ctx)


class altaPost(LoginRequiredMixin, CreateView):
	model = 'post'
	template_name = 'post/Alta.html'
	form_class = Formulario_alta_post
	success_url = reverse_lazy('post:listar_post')





# CLASE.objects.all()   RETORNA TODOS

# CLASE.objects.get()   RETORNA SOLO 1 OBJETO (SOLO FUNCIONA SI ESTOY SEGURO QUE VA RETORNAR UNO)

# CLASE.objects.filter() RETORNA VARIOS QUE CUMPLAN CON LA CONDICION

EcoGreen/apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.

EcoGreen/templates/EcoGreen.html
{% extends 'base.html' %}


{% block contenido %}
	<link rel="stylesheet" href="main.css"
	<body>
		<div id="container">
			<header>
	<p class="texto-cont">BIENVENIDOS A ECOGREEN</p>
			</header>
		<nav>
		<ul>
			<li>
	<a href="{% url 'post:alta_post' %}">CREAR POST</a><br>
			</ul>
		</li>

		<ul>
			<li>
	<a href="{% url 'post:listar_post' %}">IR A POSTS</a><br>
	<br><br>
</ul>
</li>
<br><br>

<ul>
<li>

</nav>

	{% for r in Categoria%}
	<ul>
		<li>
			<br><br>
</ul>
</li>
<br><br>


	<a href="{% url 'post:filtro' r.pk %}">
		VER DEL Categoria {{r.nombre}}
		<br><br>
	</ul>
	</li>
	<br><br>
	
	</nav>
	<div class="clearfix"></div>

	</a><br>
	
	{% endfor %}
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>




	<br>
	<br><br>
	<br><br>
	<br><br>
	<br><br>
	<br><br>
	<br><br>
	<br><br>
	<br><br>
	<br><br>
	<br><br>
	<br><br>
	<br><br>
	<br><br>
	<br><br>
	<br><br>
	<br><br>
	

<div class="container"> <div id="disqus_thread"></div>
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://ecogreen-com.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript></div>


<footer>

	Informatorio Grupo 7 &copy; 2021
</footer>
{% endblock contenido %}

EcoGreen/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title></title>

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>
<body>

	<img src="{% static 'img/logo.jpg' %}" class="image-menu">

	<div class="menu"> 

		<br>
		<br>
		<br>
		<br>

		{% if user.is_authenticated %}
			<span>bienvenido: {{ user.username }}</span>
			<a href="{% url 'logout' %}">CERRAR SESION </a>
		{% else %}
			<a href="{% url 'login' %}">LOGIN</a>
			<a href="">REGISTRO</a>

		{% endif %}


	</div>


	{% block contenido %}



	{% endblock contenido %}


</body>

</html>

EcoGreen/templates/post/alta.html
{% extends 'base.html' %}



{% block contenido %}
			<form method="POST" enctype="multipart/form-data">{% csrf_token %}
				{{form.errors}}
				{{form.as_p}}
				<input type="submit" name="" value="CREAR">
			</form>
{% endblock contenido %}

EcoGreen/templates/post/detallePost.html
{% extends 'base.html' %}


{% block contenido %}


	<p class="texto-cont">{{ post.nombre }}</p>
	<br>

	<img src="{{ post.imagen.url }}" width="300px" height="200">
	<br>
	<b>{{post.nombre}}</b><br>
	<span>Descripcion : {{post.descripcion}}</span><br>
	<span>Categoria: {{post.categoria}}</span><br>



	<a href="{% url 'EcoGreen' %}">IR AL INICIO</a>


{% endblock contenido %}

EcoGreen/templates/post/filtroxCategoria.html
{% extends 'base.html' %}


{% block contenido %}


	<p class="texto-cont">FILTRO APLICADO :  {{categoria.nombre}}</p>
	<br>

	{% for a in post %}

	<a href="{% url 'post:detalle' a.pk %}">
	<p>
		<b>{{a.nombre}}</b><br>
		<span>Descripcion : {{a.descripcion}}</span><br>
		<span>Categoria: {{a.categoria}}</span><br>

		<img src="{{a.imagen.url}}" width="100px" height="100px">
	</p>
	</a>
	{% endfor %}



	<br>
	<a href="{% url 'EcoGreen' %}">IR AL INICIO</a>


{% endblock contenido %}

EcoGreen/templates/post/listar_post.html
{% extends 'base.html' %}


{% block contenido %}


	<p class="texto-cont">{{ "EcoGreen" }}</p>
	<br>

	<a href="{% url 'EcoGreen' %}">IR AL INICIO</a>
	<br>

	{% for a in post %}

	<a href="{% url 'post:detalle' a.pk %}">
	<p>
		<b>{{a.nombre}}</b><br>
		<span> {{a.categoria}}</span><br>

		<img src="{{a.imagen.url}}" width="100px" height="100px">
	</p>
	</a>
	{% endfor %}



	<br>
	<a href="{% url 'EcoGreen' %}">IR AL INICIO</a>


{% endblock contenido %}

EcoGreen/templates/usuarios/login.html
{% extends 'base.html' %}



{% block contenido %}
			<form method="POST">{% csrf_token %}

				{{form.errors}}
				<input type="text" name="username" placeholder="USUARIO">
				<input type="password" name="password" placeholder="PASSWORD">

				<input type="submit" name="" value="ENVIAR">
			</form>
{% endblock contenido %}